retriever:
  retriever_hf_paths:
    RAGatouille: "XThomasBU/Colbert_Index"

metadata:
  metadata_links: ["https://dl4ds.github.io/sp2024/lectures/", "https://dl4ds.github.io/sp2024/schedule/"]
  slide_base_link: "https://dl4ds.github.io"

token_config:
  cooldown_time: 60
  regen_time: 180
  tokens_left: 2000
  all_time_tokens_allocated: 1000000

misc:
  github_repo: "https://github.com/edubotics-ai/edubot-core"
  docs_website: "https://dl4ds.github.io/dl4ds_tutor/"

api_config:
  timeout: 60
