retriever:
  retriever_hf_paths:
    RAGatouille: "XThomasBU/Colbert_Index"

metadata:
  metadata_links: ["https://dl4ds.github.io/sp2024/lectures/", "https://dl4ds.github.io/sp2024/schedule/"]
  slide_base_link: "https://dl4ds.github.io"

api_config:
  timeout: 60